=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/DefaultCommands.dtd
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!ENTITY % html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://internal.avlsi.com/eng/bali/verification/w3/TR/xhtml1/DTD/xhtml1-strict.dtd">
%html;
<!ENTITY % htmlpassthru "a | abbr | acronym | address | applet | area | b | base | basefont | bdo | big | blockquote  | body | br | button | caption | center | cite | code | col | colgroup | dd | del | dfn | dir | div | dl | dt | em | fieldset | font | form | frame | frameset | h1 | h2 | h3 | h4 | h5 | h6 | head | hr | html | i | iframe | img | input | ins | isindex | kbd | label | legend | li | link | map | menu | meta | noframes | noscript | object | ol | optgroup | option | p | param | pre | q | s | samp | script | select | small | span | strike | strong | style | sub | sup | table | tbody | td | textarea | tfoot | th | thead | title | tr | tt | u | ul | var">
<!ELEMENT config (command+, include*)>
  <!ELEMENT command (filter*, name, help?, description?, handler?, (command?, argument?)+)>
    <!-- filter -->
    <!-- name -->
    <!-- help -->
    <!-- description -->
    <!ELEMENT handler (#PCDATA)>
    <!ELEMENT argument (filter*, name, help?, description?, argument*)>
      <!-- filter -->
      <!-- name -->
      <!-- help -->
      <!-- description -->
  <!ELEMENT include EMPTY>
    <!ATTLIST include file CDATA #REQUIRED>


<!ELEMENT filter ((allow?, deny?)+)>
  <!ATTLIST filter type CDATA #REQUIRED>
  <!ELEMENT allow (#PCDATA)>
  <!ELEMENT deny (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT help (#PCDATA)>
<!ELEMENT description (#PCDATA|%htmlpassthru;)*>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/SFlowCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>
    <command>
        <name>add</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>sFlow</name>
            <help>Add ports to the sFlow instance</help>
                <handler>tpHandleAddSFlowPort</handler>

                <argument>
                    <name>!&lt;sFlow Id&gt;</name>
                    <help>The sFlow identifier</help>
                    <argument>
                        <name>!&lt;port&gt;</name>
                        <help>
                            The port number
                        </help>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>
                                    Include the specified port in the
                                    sFlow instance
                                </help>
                            </argument>
                    </argument>
                </argument>
         </command>
    </command>

    <command>
        <name>del</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>sFlow</name>
            <help>Delete a sFlow instance</help>
                <handler>tpHandleDeleteSFlow</handler>
                <argument>
                    <name>!&lt;sFlow Id&gt;</name>
                    <help>The sFlow identifier</help>
                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>
                                Delete the sFlow instance
                            </help>
                        </argument>
                </argument>
            <command>
                <name> port </name>
                <help> Delete ports from the sFlow </help>
                    <handler>tpHandleDeleteSFlowPort</handler>
                    <argument>
                        <name>!&lt;sFlow id&gt;</name>
                        <help> The sFlow id </help>
                        <argument>
                            <name>!&lt;port&gt;</name>
                            <help>
                                The port number
                            </help>
                                <argument>
                                    <name>!&lt;cr&gt;</name>
                                    <help>
                                        Exclude the specified port in the
                                        sFlow instance
                                    </help>
                                </argument>
                        </argument>
                    </argument>
             </command>
         </command>
    </command>

    <command>
        <name>create</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>sFlow</name>
            <help>Create a sFlow instance</help>
            <handler>tpHandleCreateSFlow</handler>

            <argument>
                <name>!&lt;sFlow&gt;</name>
                <help>The sFlow identifier</help>
                <argument>
                    <name>!&lt;type&gt;</name>
                    <help>
                        "ingress" or "egress"
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Create a sFlow instance</help>
                    </argument>
                </argument>
            </argument>
        </command>
    </command>

    <command>
        <name>set</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>sFlow</name>
            <help>Set sFlow attribute</help>
            <handler>tpHandleSetSFlowAttribute</handler>

            <argument>
                <name>!&lt;sFlow&gt;</name>
                <help>The sFlow identifier</help>
                <argument>
                    <name>vlan</name>
                    <help>Set the vlan for the sFlow</help>
                    <argument>
                        <name>!&lt;vlan id&gt;</name>
                        <help>The vlan associated with the sFlow</help>
                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Set the vlan for the sFlow</help>
                        </argument>
                    </argument>
                </argument>
                <argument>
                    <name>sampleRate</name>
                    <help>Set the sampling rate</help>
                    <argument>
                        <name>!&lt;sampling rate&gt;</name>
                        <help>
                            The packet sampling rate in percentage
                        </help>
                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Set the sampling rate</help>
                        </argument>
                    </argument>
                </argument>
                <argument>
                    <name>truncLength</name>
                    <help>Set the truncation length</help>
                    <argument>
                        <name>!&lt;truncLength&gt;</name>
                        <help>
                            The packet truncation Length
                        </help>
                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Set the trunc Length</help>
                        </argument>
                    </argument>
                </argument>
            </argument>
        </command>
    </command>

    <command>
        <name>show</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>sFlow</name>
            <help>Show sFlow properties</help>
            <handler>tpHandleShowSFlow</handler>

            <argument>
                <name>!&lt;sFlow&gt;</name>
                <help>The sFlow identifier</help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Show sFlow properties</help>
                </argument>
            </argument>
        </command>
    </command>
</config>
