=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/DefaultCommands.dtd
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!ENTITY % html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://internal.avlsi.com/eng/bali/verification/w3/TR/xhtml1/DTD/xhtml1-strict.dtd">
%html;
<!ENTITY % htmlpassthru "a | abbr | acronym | address | applet | area | b | base | basefont | bdo | big | blockquote  | body | br | button | caption | center | cite | code | col | colgroup | dd | del | dfn | dir | div | dl | dt | em | fieldset | font | form | frame | frameset | h1 | h2 | h3 | h4 | h5 | h6 | head | hr | html | i | iframe | img | input | ins | isindex | kbd | label | legend | li | link | map | menu | meta | noframes | noscript | object | ol | optgroup | option | p | param | pre | q | s | samp | script | select | small | span | strike | strong | style | sub | sup | table | tbody | td | textarea | tfoot | th | thead | title | tr | tt | u | ul | var">
<!ELEMENT config (command+, include*)>
  <!ELEMENT command (filter*, name, help?, description?, handler?, (command?, argument?)+)>
    <!-- filter -->
    <!-- name -->
    <!-- help -->
    <!-- description -->
    <!ELEMENT handler (#PCDATA)>
    <!ELEMENT argument (filter*, name, help?, description?, argument*)>
      <!-- filter -->
      <!-- name -->
      <!-- help -->
      <!-- description -->
  <!ELEMENT include EMPTY>
    <!ATTLIST include file CDATA #REQUIRED>


<!ELEMENT filter ((allow?, deny?)+)>
  <!ATTLIST filter type CDATA #REQUIRED>
  <!ELEMENT allow (#PCDATA)>
  <!ELEMENT deny (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT help (#PCDATA)>
<!ELEMENT description (#PCDATA|%htmlpassthru;)*>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/VNCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>


<!-- create -->
<command>
    <name>create</name>
    <help>Create VLANs, LAGs, multicast groups, ACLs, etc.</help>

    <!-- create virtual-network -->
    <command>
        <name>virtual-network</name>
        <help>Create a Virtual Network</help>
        <handler>tpHandleCreateVN</handler>

        <!-- create virtual-network <vsid> -->
        <argument>
            <name>!&lt;vsid&gt;</name>
            <help>Virtual Subscriber ID</help>

            <!-- create virtual-network <vsid> <internal-id> -->
            <argument>
                <name>!&lt;internalId&gt;</name>
                <help>Internal ID number to associate with this vsid</help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Create Virtual Network</help>
                </argument>
            </argument> <!-- <internal-id> -->
        </argument> <!-- <vsid> -->
    </command> <!-- end create virtual-network -->

    <!-- create vn-tunnel -->
    <command>
        <name>vn-tunnel</name>
        <help>Create a Virtual Network Tunnel</help>
        <handler>tpHandleCreateVNTunnel</handler>

        <!-- create vn-tunnel vxlan -->
        <argument>
            <name>vxlan</name>
            <help>Create a VxLAN Virtual Network Tunnel</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Create Virtual Network Tunnel</help>
            </argument>
        </argument> <!-- vxlan -->

        <!-- create vn-tunnel nvgre -->
        <argument>
            <name>nvgre</name>
            <help>Create an NVGRE Virtual Network Tunnel</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Create Virtual Network Tunnel</help>
            </argument>
        </argument> <!-- vxlan -->
    </command> <!-- end create vn-tunnel -->

</command>  <!-- end create -->


<!-- del -->
<command>
    <name>del</name>
    <help>Delete VLANs, LAGs, multicast groups, ACLs, etc.</help>

    <!-- del virtual-network -->
    <command>
        <name>virtual-network</name>
        <help>Delete a Virtual Network</help>
        <handler>tpHandleDeleteVN</handler>

        <!-- del virtual-network <vsid> -->
        <argument>
            <name>!&lt;vsid&gt;</name>
            <help>Virtual Subscriber ID</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Delete Virtual Network</help>
            </argument>
        </argument> <!-- <vsid> -->
    </command> <!-- end del virtual-network -->

    <!-- del vn-tunnel -->
    <command>
        <name>vn-tunnel</name>
        <help>Delete a Virtual Network Tunnel</help>
        <handler>tpHandleDeleteVNTunnel</handler>

        <!-- del vn-tunnel <tunnel-id> -->
        <argument>
            <name>!&lt;tunnelid&gt;</name>
            <help>VN Tunnel ID</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Delete Virtual Network Tunnel</help>
            </argument>
        </argument> <!-- <tunnel-id> -->
    </command> <!-- end del vn-tunnel -->

</command>  <!-- end del -->


<!-- set -->
<command>
    <name>set</name>
    <help>Set a property</help>

    <!-- set virtual-network -->
    <command>
        <filter type="family">
            <deny>FM2000</deny>
            <deny>FM4000</deny>
        </filter>
        <name>virtual-network</name>
        <help>Set a virtual network related property</help>

        <!-- set virtual-network internal-id -->
        <command>
            <name>internal-id</name>
            <help>Set the virtual network's internal ID</help>
            <handler>tpHandleSetVNInternalID</handler>

            <argument>
                <name>vsid</name>
                <help>The Virtual Network ID #</help>
                <argument>
                    <name>!&lt;vsid&gt;</name>
                    <help>
                        The virtual subscriber ID number
                    </help>
                    <argument>
                        <name>!&lt;internalId&gt;</name>
                        <help>
                            The new internal ID for this virtual network.
                        </help>
                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help> </help>
                        </argument>
                    </argument>
                </argument>
            </argument> <!-- end internal-id -->
        </command>  <!-- end set virtual-network internal-id -->
    </command> <!-- end set virtual-network -->

    <!-- set vn-tunnel -->
    <command>
        <filter type="family">
            <deny>FM2000</deny>
            <deny>FM4000</deny>
        </filter>
        <name>vn-tunnel</name>
        <help>Set a virtual network tunnel-related property</help>
        <handler>tpHandleSetVNTunnelAttribute</handler>

        <!-- set vn-tunnel <tunnel-list> -->
        <argument>
            <name>!&lt;tunnelId&gt;</name>
            <help>A tunnel number, list, range, or combination thereof)</help>

            <!-- set vn-tunnel <tunnel> local-ip <localIp> -->
            <argument>
                <name>local-ip</name>
                <help>Set the vn-tunnel's local IP address</help>
                <argument>
                    <name>!&lt;localIp&gt;</name>
                    <help>
                        The new local IP Address for this virtual network tunnel.
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help> </help>
                    </argument>
                </argument> <!-- end local-ip -->
            </argument> <!--- end set vn-tunnel <tunnel> local-ip -->

            <!-- set vn-tunnel <tunnel> remote-ip -->
            <argument>
                <name>remote-ip</name>
                <help>Set the vn-tunnel's remote IP address</help>
                <argument>
                    <name>!&lt;remoteIp&gt;</name>
                    <help>
                        The new remote IP Address for this virtual network tunnel.
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help> </help>
                    </argument>
                </argument> <!-- end remote-ip -->
            </argument>  <!-- end set vn-tunnel <tunnel> remote-ip -->

            <!-- set vn-tunnel <tunnel> traffic-identifier -->
            <argument>
                <name>traffic-identifier</name>
                <help>Set the vn-tunnel's traffic identifier</help>
                <argument>
                    <name>!&lt;trafficid&gt;</name>
                    <help>
                        The new traffic identifier for this virtual network tunnel.
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help> </help>
                    </argument>
                </argument> <!-- end trafficid -->
            </argument>  <!-- end set vn-tunnel <tunnel> traffic-identifier -->

            <!-- set vn-tunnel <tunnel> vrid -->
            <argument>
                <name>vrid</name>
                <help>Set the vn-tunnel's virtual router ID number</help>
                <argument>
                    <name>!&lt;vrid&gt;</name>
                    <help>
                        The new virtual router ID for this virtual network tunnel.
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help> </help>
                    </argument>
                </argument> <!-- end vrid -->
            </argument>  <!-- end set vn-tunnel <tunnel> vrid -->

            <!-- set vn-tunnel mcast-group -->
            <argument>
                <name>mcast-group</name>
                <help>Set the vn-tunnel's multicast group</help>
                <argument>
                    <name>!&lt;mcastGroup&gt;</name>
                    <help>
                        The new multicast group used with this virtual network tunnel.
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help> </help>
                    </argument>
                </argument> <!-- end mcast-group -->
            </argument>  <!-- end set vn-tunnel <tunnel> mcast-group -->

            <!-- set vn-tunnel <tunnel> mcast-dmac -->
            <argument>
                <name>mcast-dmac</name>
                <help>Set the multicast vn-tunnel's destination MAC address</help>
                <argument>
                    <name>!&lt;dmacaddr&gt;</name>
                    <help>
                        The new destination MAC address for this multicast virtual network tunnel.
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help> </help>
                    </argument>
                </argument> <!-- end <dmacaddr> -->
            </argument>  <!-- end set vn-tunnel <tunnel> mcast-dmac -->

        </argument> <!-- end set vn-tunnel -->
    </command> <!-- end set vn-tunnel -->

</command> <!-- end set -->


</config>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/LoadBalancingCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>

    <!-- set -->
    <command>
        <name>set</name>

        <!-- set loadbalancing -->
        <command>
            <filter type="family">
                <allow>FM4000</allow>
            </filter>
            <filter type="switch-count">
                <allow>1</allow>
            </filter>

            <name>loadbalancing</name>
            <help>Set load balacing properties</help>
            <handler>tpHandleSetLoadBalancing</handler>

            <!-- set loadbalancing enable -->
            <argument>
                <name>enable</name>
                <help>enable load balancing</help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>enable load balancing</help>
                </argument>
            </argument><!--enable-->

            <!-- set loadbalancing match -->
            <argument>
                <name>match</name>
                <help>frame matching options</help>

                <argument>
                    <name>dip</name>
                    <help>set matching condition with destination IP</help>
                    <argument>
                        <name>!&lt;dip&gt;</name>
                        <help>destination IPv4 address e.g. 192.168.1.1</help>
                    </argument>
                </argument> <!-- dip -->
            </argument> <!-- match -->

            <!-- set loadbalancing distribution -->
            <argument>
                <name>distribution</name>
                <help>load distribution options</help>

                <argument>
                    <name>uniform</name>
                    <help>uniform bin to load balancing port assignment</help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>set loadbalancing distribution uniform</help>
                    </argument>
                </argument> <!-- uniform -->

                <argument>
                    <name>custom</name>
                    <help>custom bin to load balancing port assignment</help>

                    <argument>
                        <name>!&lt;bin&gt;</name>
                        <help>bin number to set load balancing port for</help>
                        <argument>
                            <name>!&lt;loadbalport&gt;</name>
                            <help>load balancing port to select for this
                            bin</help>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>set loadbalancing distribution custom</help>
                            </argument>
                        </argument>
                    </argument> <!-- <bin> -->
                </argument> <!-- custom -->

            </argument> <!-- distribution -->

            <!-- set loadbalancing portlist -->
            <argument>
                <name>portlist</name>
                <help>logical ports in load balancing group, e.g. 
                set loadbalancing portlist 1,2,3,4</help>

                <argument>
                    <name>!&lt;portlist&gt;</name>
                    <help>comma separated logical port list, e.g. 1,2,3,4
                    </help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>set loadbalancing portlist</help>
                    </argument>
                </argument> <!-- <portlist> -->
            </argument> <!-- portlist -->
            
        </command>  <!-- end set loadbalancing -->

    </command>  <!-- end set -->

    <!-- show -->
    <command>
        <name>show</name>

        <!-- show loadbalancing -->
        <command>
            <filter type="family">
                <allow>FM4000</allow>
            </filter>
            <filter type="switch-count">
                <allow>1</allow>
            </filter>

            <name>loadbalancing</name>
            <help>Show load balancing properties</help>
            <handler>tpHandleShowLoadBalancing</handler>

            <!-- show loadbalancing distribution -->
            <argument>
                <name>distribution</name>
                <help>show the bin to load balancing port distribution
                </help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>show loadbalancing distribution</help>
                </argument>
            </argument>

        </command>  <!-- end show loadbalancing -->
    </command>  <!-- end show -->

</config>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/StreamCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>

<!--
<argument>
    <name>!&lt;cr&gt;</name>
    <help></help>
</argument>
-->

<command>
    <name>set</name>

    <command>
        <name>stream</name>
        <help>Modify stream mode or output ports</help>

        <command>
            <name>port</name>
            <help>Set the output ports of a stream</help>
            <handler>tpSetStreamPort</handler>

            <argument>
                <name>!&lt;streamId&gt;</name>
                <help>The stream whose contents will be forwarded out this port</help>

                <argument>
                    <name>!&lt;port(s)&gt;</name>
                    <help>The port or list of ports to add</help>

                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Set output port(s) of a stream</help>
                    </argument>

                </argument>

            </argument>

        </command>

        <command>
            <name>mode</name>
            <help>Start, stop or burst a stream contents out</help>
            <handler>tpSetStreamMode</handler>

            <argument>
                <name>!&lt;streamId&gt;</name>
                <help>The stream to start, stop or burst</help>

                <argument>
                    <name>loop-start</name>
                    <help>Start looping the stream contents to output port(s)</help>

                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Start looping traffic</help>
                    </argument>

                </argument>

                <argument>
                    <name>loop-stop</name>
                    <help>Stop transmit of stream contents to output port(s).</help>

                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Stop transmit of looping traffic</help>
                    </argument>

                </argument>

                <argument>
                    <name>release</name>
                    <help>Empty the stream contents to output port(s)</help>

                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Burst one copy of traffic, emptying stream</help>
                    </argument>

                </argument>

                <argument>
                    <name>clear</name>
                    <help>Flush contents of the stream</help>

                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Flush contents of the stream</help>
                    </argument>

                </argument>


            </argument>

        </command>

    </command>
</command>

<command>
    <name>del</name>

    <command>
        <name>stream</name>
        <help>Delete a stream from the system</help>
        <handler>tpDeleteStream</handler>

            <argument>
                <name>!&lt;streamId&gt;</name>
                <help>The stream to delete (loopback port number)</help>

                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Delete a stream</help>
                </argument>

            </argument>

    </command>
</command>

<command>
    <name>create</name>

    <command>
        <name>stream</name>
        <help>Create a stream for traffic generation</help>
        <handler>tpCreateStream</handler>

        <argument>
            <name>!&lt;port&gt;</name>
            <help>Set the port to use in loopback (streamID)</help>
            
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Loopback a port to use as a stream</help>
            </argument>
        
        </argument>

    </command>

</command>

<command>
    <name>reset</name>

    <command>
        <name>stream</name>
        <help>Drain any farmes in the stream</help>
        <handler>tpResetStream</handler>

          <argument>
          <name>!&lt;port&gt;</name>
          <help>Drain any traffic in the stream</help>

              <argument>
              <name>!&lt;cr&gt;</name>
              <help>Drain the stream of traffic</help>
              </argument>

          </argument>

    </command>

</command>

<command>
    <name>add</name>

    <command>
        <name>stream</name>
        <help>Add packets to a stream</help>

        <command>
            <name>packet</name>
            <help>Add packets to a stream</help>
            <handler>tpAddStreamPacket</handler>

            <argument>
                <name>!&lt;streamId&gt;</name>
                <help>The stream to add the packet(s) to</help>

                <argument>
                    <name>file-pcap</name>
                    <help>Add a sequence of packet in a PCAP file</help>

                    <argument>
                        <name>!&lt;filename&gt;</name>
                        <help>File containing the frames (timestamps are ignored)</help>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>Load these packets into the stream</help>
                            </argument>
                    </argument>
                </argument>

                <argument>
                    <name>bytes</name>
                    <help>Add the packet as bytes</help>

                    <argument>
                        <name>!&lt;length&gt;</name>
                        <help>The packet length in bytes</help>


                        <argument>
                            <name>!&lt;DMAC&gt;</name>
                            <help>The destination MAC in the form XX:XX:XX:XX:XX:XX</help>

                            <argument>
                                <name>!&lt;SMAC&gt;</name>
                                <help>The source MAC in the form XX:XX:XX:XX:XX:XX</help>

                                <argument>
                                    <name>!&lt;value&gt;</name>
                                    <help>Hexadecimal payload byte values</help>
                                    <argument>
                                        <name>!&lt;cr&gt;</name>
                                        <help>Load this packet into the stream</help>
                                    </argument>
                                </argument>
                                <argument>
                                    <name>!&lt;cr&gt;</name>
                                    <help>Send the packet, filling in the payload as needed</help>
                                </argument>
                            </argument>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>Send the packet, filling in the payload as needed</help>
                            </argument>
                        </argument>
                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Send the packet, filling in the payload as needed</help>
                        </argument>
                    </argument>
                </argument>

            </argument>

        </command>

    </command>
</command>

</config>
