=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/DefaultCommands.dtd
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!ENTITY % html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://internal.avlsi.com/eng/bali/verification/w3/TR/xhtml1/DTD/xhtml1-strict.dtd">
%html;
<!ENTITY % htmlpassthru "a | abbr | acronym | address | applet | area | b | base | basefont | bdo | big | blockquote  | body | br | button | caption | center | cite | code | col | colgroup | dd | del | dfn | dir | div | dl | dt | em | fieldset | font | form | frame | frameset | h1 | h2 | h3 | h4 | h5 | h6 | head | hr | html | i | iframe | img | input | ins | isindex | kbd | label | legend | li | link | map | menu | meta | noframes | noscript | object | ol | optgroup | option | p | param | pre | q | s | samp | script | select | small | span | strike | strong | style | sub | sup | table | tbody | td | textarea | tfoot | th | thead | title | tr | tt | u | ul | var">
<!ELEMENT config (command+, include*)>
  <!ELEMENT command (filter*, name, help?, description?, handler?, (command?, argument?)+)>
    <!-- filter -->
    <!-- name -->
    <!-- help -->
    <!-- description -->
    <!ELEMENT handler (#PCDATA)>
    <!ELEMENT argument (filter*, name, help?, description?, argument*)>
      <!-- filter -->
      <!-- name -->
      <!-- help -->
      <!-- description -->
  <!ELEMENT include EMPTY>
    <!ATTLIST include file CDATA #REQUIRED>


<!ELEMENT filter ((allow?, deny?)+)>
  <!ATTLIST filter type CDATA #REQUIRED>
  <!ELEMENT allow (#PCDATA)>
  <!ELEMENT deny (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT help (#PCDATA)>
<!ELEMENT description (#PCDATA|%htmlpassthru;)*>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/RBridgeCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>

<!-- show -->
<command>
    <name>show</name>
    <help>Show a property</help>

    <!-- show rbridge -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge</name>
        <help>Show a remote RBridge</help>
        <handler>tpHandleShowRBridge</handler>

        <!-- show rbridge <tunnelId> -->
        <argument>
            <name>!&lt;tunnelId&gt;</name>
            <help>Virtual tunnel ID</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Show all remote RBridges</help>
            </argument>
        </argument> <!-- end show rbridge <tunnelIds> -->
    </command>  <!-- end show rbridge -->

    <!-- show rbridge-disttree -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge-disttree</name>
        <help>Show a RBridge Distribution Tree</help>
        <handler>tpHandleShowRBridgeDistTree</handler>

        <!-- show rbridge-disttree <tunnelId> -->
        <argument>
            <name>!&lt;tunnelId&gt;</name>
            <help>Virtual tunnel ID</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Show all RBridge Distribution Trees</help>
            </argument>
        </argument> <!-- end show rbridge-disttree <tunnelIds> -->
    </command>  <!-- end show rbridge-disttree -->

</command>  <!-- end show -->

<!-- del -->
<command>
    <name>del</name>
    <help>Delete MAC address, VLANs, LAGs, or ports from VLANs, or counters from VLANs or LAGs</help>

    <!-- del rbridge -->
    <command>
        <name>rbridge</name>
        <help>Delete a RBridge node</help>
        <handler>tpHandleDeleteRBridge</handler>

        <!-- del rbridge <tunnelId> -->
        <argument>
            <filter type="family">
                <allow>FM6000</allow>
            </filter>
            <name>!&lt;tunnelId&gt;</name>
            <help>Virtual tunnel ID to reference the specific RBridge node to delete</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Delete the RBridge referenced by this virtual tunneId</help>
            </argument>
        </argument> <!-- <tunnelId> -->
    </command>  <!-- end del rbridge -->

    <!-- del rbridge-disttree -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge-disttree</name>
        <help>Delete a RBridge Distribution Tree</help>
        <handler>tpHandleDeleteRBridgeDistTree</handler>

        <!-- del rbridge-disttree <tunnelId> -->
        <argument>
            <name>!&lt;tunnelId&gt;</name>
            <help>Virtual tunnel ID to reference the specific RBridge Distribution Tree to delete</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Delete the RBridge Distribution Tree referenced by this virtual tunneId</help>
            </argument>
        </argument> <!-- <tunnelId> -->
    </command>  <!-- end del rbridge -->

</command>  <!-- end del -->


<!-- create -->
<command>
    <name>create</name>
    <help>Create VLANs, LAGs, multicast groups, ACLs, etc.</help>

    <!-- create rbridge -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge</name>
        <help>Create a remote RBridge</help>
        <handler>tpHandleCreateRBridge</handler>

        <!-- create rbridge <mac> -->
        <argument>
            <name>!&lt;mac&gt;</name>
            <help>NextHop RBridge MAC used to reach this remote RBridge</help>

            <!-- create rbridge <mac> <nickname> -->
            <argument>
                <name>!&lt;nickname&gt;</name>
                <help>Remote RBridge NickName (16-bit value)</help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Create the specified remote RBridge</help>
                </argument>
            </argument> <!-- <nickname> -->
        </argument> <!-- <mac> -->
    </command> <!-- end create rbridge -->

    <!-- create rbridge-disttree -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge-disttree</name>
        <help>Create a RBridge Distribution Tree</help>
        <handler>tpHandleCreateRBridgeDistTree</handler>

        <!-- create rbridge-disttree <nickname> -->
        <argument>
            <name>!&lt;nickname&gt;</name>
            <help>RBridge Distribution Tree  (16-bit value) to create</help>
            <!-- create rbridge-disttree <nickname> <hopcnt>-->
            <argument>
                <name>!&lt;hopcnt&gt;</name>
                <help>Set RBridge Distribution Tree Hop Count</help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Create the specified RBridge Distribution Tree</help>
                </argument>
            </argument> <!-- end create rbridge-disttree <nickname> <hopcnt> -->

            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Create the specified RBridge Distribution Tree</help>
            </argument>
        </argument> <!-- end create rbridge-disttree <nickname> -->
    </command>  <!-- end create rbridge-disttree -->

</command>  <!-- end create -->

<!-- set -->
<command>
    <name>set</name>
    <help>Set a property</help>

    <!-- set rbridge -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge</name>
        <help>Update a remote RBridge entry</help>
        <handler>tpHandleUpdateRBridge</handler>

        <!-- set rbridge <tunnelId> -->
        <argument>
        <name>!&lt;tunnelId&gt;</name>
        <help>Virtual tunnel ID to reference the specific RBridge node to delete</help>

            <!-- set rbridge <tunnelId> <mac> -->
            <argument>
                <name>!&lt;mac&gt;</name>
                <help>NextHop RBridge MAC used to reach this remote RBridge</help>

                <!-- set rbridge <tunnelId> <mac> <nickname> -->
                <argument>
                    <name>!&lt;nickname&gt;</name>
                    <help>Remote RBridge NickName (16-bit value)</help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Update the specified remote RBridge</help>
                    </argument>
                </argument> <!-- <nickname> -->
            </argument> <!-- <mac> -->
        </argument> <!-- <tunnelId> -->
    </command> <!-- end set rbridge -->

    <!-- set rbridge-disttree -->
    <command>
        <filter type="family">
            <allow>FM6000</allow>
        </filter>
        <name>rbridge-disttree</name>
        <help>Update a RBridge Distribution Tree entry</help>
        <handler>tpHandleUpdateRBridgeDistTree</handler>

        <argument>
            <!-- set rbridge-disttree <tunnelId> -->
            <name>!&lt;tunnelId&gt;</name>
            <help>Virtual tunnel ID to reference the specific RBridge Distribution Tree to delete</help>

            <!-- set rbridge-disttree <tunnelId> <nickname> -->
            <argument>
                <name>!&lt;nickname&gt;</name>
                <help>RBridge Distribution Tree  (16-bit value) to update</help>
                <!-- set rbridge-disttree <tunnelId> <nickname> <hopcnt>-->
                <argument>
                    <name>!&lt;hopcnt&gt;</name>
                    <help>Update RBirdge Distribution Tree Hop Count</help>
                    <argument>
                        <name>!&lt;cr&gt;</name>
                        <help>Update the specified RBridge Distribution Tree</help>
                    </argument>
                </argument> <!-- <hopcnt> -->

                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Update the specified RBridge Distribution Tree</help>
                </argument>
            </argument> <!-- <nickname> -->
        </argument> <!-- <tunnelId> -->
    </command>  <!-- end set rbridge-disttree -->

</command>  <!-- end set -->

</config>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/CongestionNotificationCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>

    <command>
        <name>set</name>
            <command>
                <name>switch</name>
                <command>
                    <name>config</name>
                    <command>
                        <filter type="family">
                            <allow>FM4000</allow>
                        </filter>
                        <name>cn</name>
                        <help>Set congestion notification properties</help>
                        <handler>tpHandleSetCN</handler>
                        <argument>
                            <name>mode</name>
                            <help>Sets the congestion notification mode</help>
                            <argument>
                                <name>off</name>
                                <help>Disable congestion notification</help>
                                <argument>
                                    <name>!&lt;cr&gt;</name>
                                    <help>Set the congestion notification mode</help>
                                </argument>
                            </argument>
                            <argument>
                                <name>vcn</name>
                                <help>Enable VOQ Congestion Notification</help>
                                <argument>
                                    <name>!&lt;cr&gt;</name>
                                    <help>Set the congestion notification mode</help>
                                </argument>
                            </argument>
                            <argument>
                                <name>bcn</name>
                                <help>Enable Backwards Congestion Notification</help>
                                <argument>
                                    <name>!&lt;cr&gt;</name>
                                    <help>Set the congestion notification mode</help>
                                </argument>
                            </argument>
                            <argument>
                                <name>scn</name>
                                <help>Enable Simple Congestion Notification</help>
                                <argument>
                                    <name>!&lt;cr&gt;</name>
                                    <help>Set the congestion notification mode</help>
                                </argument>
                            </argument>
                        </argument><!--mode-->
                    </command><!--cn-->
                </command><!--config-->
            </command><!--switch-->

    </command><!--set-->

    <command>
        <name>show</name>
            <command>
                <name>switch</name>
                <command>
                    <name>config</name>
                    <command>
                        <filter type="family">
                            <allow>FM4000</allow>
                        </filter>
                        <name>cn</name>
                        <help>Show congestion notification properties</help>
                        <handler>tpHandleShowCN</handler>
                        <argument>
                            <name>mode</name>
                            <help>show CN mode</help>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>Show congestion notification mode</help>
                            </argument>
                        </argument><!--mode-->
                    </command><!--cn-->
                </command><!--config -->
            </command><!--switch -->

    </command><!--show-->

</config>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/StackingCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>

<!--
<argument>
    <name>!&lt;cr&gt;</name>
    <help></help>
</argument>
-->

<command>
    <name>create</name>

    <command>
        <name>stacking</name>
        <help>Create objects for stacking switches</help>

        <command>
            <name>forwarding-rule</name>
            <help>Create a forwarding rule for stacking</help>
            <handler>tpCreateForwardingRule</handler>

            <argument>
                <name>!&lt;glort&gt;</name>
                <help>The glort value to forward</help>

                <argument>
                    <name>!&lt;mask&gt;</name>
                    <help>The associated glort mask</help>

                    <argument>
                        <name>!&lt;port&gt;</name>
                        <help>The logical port to forward to</help>

                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Create a forwarding rule for stacking</help>
                        </argument>

                    </argument>

                </argument>

            </argument>

        </command>

        <command>
            <name>logical-port</name>
            <help>Create a logical port for stacking</help>
            <handler>tpCreateStackLogicalPort</handler>

            <argument>
                <name>!&lt;glort&gt;</name>
                <help>The glort value to associate</help>

                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Associate a logical port number with a glort</help>
                </argument>

            </argument>

        </command>
    </command>
</command>

<command>
    <name>del</name>

    <command>
        <name>stacking</name>
        <help>Delete objects for stacking switches</help>

        <command>
            <name>forwarding-rule</name>
            <help>Delete a forwarding rule for stacking</help>
            <handler>tpDeleteForwardingRule</handler>

            <argument>
                <name>!&lt;id&gt;</name>
                <help>The forwarding rule ID to delete</help>

                <argument>
                    <name>!&lt;cr!&gt;</name>
                    <help>Delete a forwarding rule for stacking</help>
                </argument>

            </argument>

        </command>
        <command>
            <name>logical-port</name>
            <help>Delete a logical port for stacking</help>
            <handler>tpDeleteStackLogicalPort</handler>

            <argument>
                <name>!&lt;logical-port&gt;</name>
                <help>The logucal port to delete</help>

                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Delete a logical port to glort association.</help>
                </argument>

            </argument>

        </command>

    </command>
</command>

<command>
    <name>set</name>

    <command>
        <name>stacking</name>
        <help>Set switch stacking parameters</help>

        <command>
            <name>internal-port</name>
            <help>Configure a port as internal</help>
            <handler>tpSetStackInternalPort</handler>

              <argument>
              <name>!&lt;port&gt;</name>
              <help>Set the port</help>

                  <argument>
                  <name>!&lt;cr&gt;</name>
                  <help>Configure a port as internal</help>
                  </argument>

              </argument>

        </command>

        <command>
            <name>glort-range</name>
            <help>Set glort range for the given switch (requires chip reset, if up)</help>
            <handler>tpSetStackGlortRange</handler>

              <argument>
              <name>!&lt;switch&gt;</name>
              <help>The switch number</help>
              
                <argument>
                <name>!&lt;glort&gt;</name>
                <help>Set the glort value used</help>

                  <argument>
                  <name>!&lt;mask&gt;</name>
                  <help>Set the glort mask used</help>

                      <argument>
                      <name>!&lt;cr&gt;</name>
                      <help>Configure the glort mask used for this forwarding rule</help>
                      </argument>

                  </argument>

                </argument>

            </argument>

        </command>

        <command>
            <name>forwarding-rule</name>
            <help>Set properties of an existing forwarding rule</help>
            <handler>tpSetForwardingRuleConfig</handler>

            <argument>
                <name>!&lt;id&gt;</name>
                <help>The forwarding rule ID to configure</help>

                <argument>
                    <name>glort</name>
                    <help>Set the glort value used</help>

                    <argument>
                        <name>!&lt;glort&gt;</name>
                        <help>Set the glort value used</help>

                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Configure the glort value used for this forwarding rule</help>
                        </argument>

                    </argument>

                </argument>

                <argument>
                    <name>mask</name>
                    <help>Set the glort mask used</help>

                    <argument>
                        <name>!&lt;mask&gt;</name>
                        <help>Set the glort mask used</help>

                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Configure the glort mask used for this forwarding rule</help>
                        </argument>

                    </argument>

                </argument>

                <argument>
                    <name>port</name>
                    <help>Set the logical port used</help>

                    <argument>
                        <name>!&lt;mask&gt;</name>
                        <help>Set the logical port used</help>

                        <argument>
                            <name>!&lt;cr&gt;</name>
                            <help>Configure the logical port used for this forwarding rule</help>
                        </argument>

                    </argument>

                </argument>

            </argument>

        </command>

    </command>
</command>

<command>
    <name>show</name>

    <command>
        <name>stacking</name>
        <help>Show switch stacking parameters</help>

        <command>
            <name>glort-range</name>
            <help>Show the glort range for this switch</help>
            <handler>tpShowStackGlortRange</handler>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Show the glort range for this switch</help>
            </argument>
        </command>

        <command>
            <name>glort</name>
            <help>Show the glort for the given logical port(s)</help>
            <handler>tpShowStackGlort</handler>
            <argument>
                <name>!&lt;logical port(s)&gt;</name>
                <help>The list of logical ports to lookup</help>

                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Show the glort for the given logical ports(s)</help>
                </argument>
            </argument>
        </command>

        <command>
            <name>logical-port</name>
            <help>Show the logical port for the given glort(s)</help>
            <handler>tpShowLogicalPort</handler>
            <argument>
                <name>!&lt;glort(s)&gt;</name>
                <help>The list of glorts to lookup</help>

                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Show the logical port for the given glort(s)</help>
                </argument>
            </argument>
        </command>

        <command>
            <name>forwarding-rule</name>
            <help>Show all stacking forwarding rules</help>
            <handler>tpShowForwardingRules</handler>

            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Show all stacking forwarding rules</help>
            </argument>
        </command>
    </command>
</command>

</config>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/CVlanCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>
    <command>
        <name>create</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>cVlan</name>
            <help>Create a customer vlan instance</help>
                <handler>tpHandleCreateCVlan</handler>
                <argument>
                    <name>!&lt;port&gt;</name>
                    <help>The port to map from</help>
                    <argument>
                        <name>!&lt;cVlan&gt;</name>
                        <help>
                            The cVlan ID to map from
                        </help>
                        <argument>
                            <name>!&lt;sVlan&gt;</name>
                            <help>
                                The sVlan ID to map to
                            </help>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>
                                    Create a cVlan instance    
                                </help>
                            </argument>
                         </argument>
                    </argument>
                </argument>
         </command>
    </command>

    <command>
        <name>del</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>cVlan</name>
            <help>Delete a cVlan instance</help>
                <handler>tpHandleDeleteCVlan</handler>
                <argument>
                    <name>!&lt;port&gt;</name>
                    <help>The port of the cVlan instance</help>
                        <argument>
                            <name>!&lt;cVlan&gt;</name>
                            <help>The cVlan ID of the cVlan instance</help>
                            <argument>
                                <name>!&lt;cr&gt;</name>
                                <help>
                                    Delete the sFlow instance
                                </help>
                            </argument>
                         </argument>
                </argument>
         </command>
    </command>

    <command>
        <name>show</name>
        <command>
            <filter type="family">
                <deny>FM2000</deny>
            </filter>
            <name>cVlans</name>
            <help>List all cVlans </help>
            <handler>tpHandleShowCVlans</handler>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Show all cVlans</help>
                </argument>
        </command>
    </command>

</config>

=== harryliu-intel/async-toolkit/async-toolkit/m3utils/mby-merged/ies/applications/TestPoint/Config/xml/UpdateCommands.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config PUBLIC "-//Fulcrum Microsystems//DTD DefaultCommands/EN" "DefaultCommands.dtd">
<!--
    vim:autoindent:et:sw=4:ts=4:tw=79:
-->

<config>

<!-- update -->
<command>
    <filter type="update-support">
        <allow>STARTUP2.0</allow>   <!-- only for startup 2.0 or later on the CF  -->
    </filter>

    <name>update</name>
    <help>TestPoint update commands</help>

    <!-- update show -->
    <command>
        <name>show</name>
        <help>Show update related information</help>
        <!-- update show repository-->
        <command>
            <name>repository</name>
            <help>Show tarballs in the repository</help>
            <handler>tpHandleUpdateShowRepository</handler>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Display tarballs in the repository</help>
            </argument>
        </command>  <!-- end update show repository-->
        <!-- update show image information-->
        <command>
            <name>info</name>
            <help>Show information about the current TestPoint image</help>
            <handler>tpHandleUpdateShowImageInformation</handler>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Show current image information</help>
            </argument>
        </command> <!-- end update show image information-->
    </command> <!-- end update show -->
    
    <!-- update install --> 
    <command>
        <name>install</name>
        <help>Install TestPoint image from repository</help>
        <handler>tpHandleUpdateInstallTpImage</handler>
        <argument>
            <name>!&lt;tarball name&gt;</name>
            <help>Tarball to use for the installation</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Install image</help>
            </argument>
        </argument>
        <argument>
            <name>!&lt;tarball num&gt;</name>
            <help>Tarball repository reference number. See "update show 
                repository"</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Install selected TestPoint image</help>
            </argument>
        </argument>
    </command> <!-- end update install -->
    
    <!-- update remove --> 
    <command>
        <name>remove</name>
        <help>Remove tarball from the repository</help>
        <handler>tpHandleUpdateRemoveTarball</handler>
        <argument>
            <name>!&lt;tarball num&gt;</name>
            <help>Tarball repository reference number. See "update show 
                repository"</help>
            <argument>
                <name>!&lt;cr&gt;</name>
                <help>Remove tarball</help>
            </argument>
        </argument>
    </command> <!-- end update remove-->

    <!-- update download --> 
    <command>
        <name>download</name>
        <help>Download tarball via TFTP</help>
        <handler>tpHandleUpdateTftpDownload</handler>
        <argument>
            <name>!&lt;tarball name&gt;</name>
            <help>Tarball to download</help>
            <argument>
                <name>!&lt;ip address&gt;</name>
                <help>TFTP server IP address</help>
                <argument>
                    <name>!&lt;cr&gt;</name>
                    <help>Download from TFTP server</help>
                </argument>
            </argument>
        </argument>
    </command> <!-- end update download-->

</command>  <!-- end update -->

</config>
